version: '3.8'

services:
  app:
    image: hw3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://FunnyRockfish:homework3@mongo:27017

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: FunnyRockfish # Замените на свой логин
      MONGO_INITDB_ROOT_PASSWORD: homework3 # Замените на свой пароль
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

volumes:
  mongo_data:
    driver: local
  mongo_config:
    driver: local